@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'All',
            defaultValue: false,
            description: 'Runs all even if there are no changes'
        )

        booleanParam(
            name: 'Dev',
            defaultValue: false,
            description: 'Runs dev even if there are no changes'
        )

        booleanParam(
            name: 'Prod',
            defaultValue: false,
            description: 'Runs prod even if there are no changes'
        )
    }

    environment {
        DEV_CLIENT_HOSTNAME = 'dev.tic-tac-toe.qrcool.ca'
        PROD_CLIENT_HOSTNAME = 'tic-tac-toe.qrcool.ca'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
        PACKAGE = 'client/package.json'
        PACKAGE_LOCK = 'client/package-lock.json'
        JENKINS = 'Jenkinsfile'
        CHANGE_SRC = 'client/src/**'
        DEV_NGINX_CONF = 'nginx.dev.conf'
        PROD_NGINX_CONF = 'nginx.prod.conf'
        DIR = 'client'
        PROJECT_NAME='tic-tac-toe'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            when {
                anyOf {
                    changeset CHANGE_SRC
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    changeset JENKINS
                    expression { return params.All || params.Dev || params.Prod }
                }
            }
            steps {
                dir(DIR) {
                    sh 'npm install'
                    loadEnvFile(PROJECT_NAME, 'client', 'development')
					loadEnvFile(PROJECT_NAME, 'client', 'production')
                }
            }
        }

        stage('Build Dev') {
            when {
                anyOf {
                    changeset CHANGE_SRC
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    changeset JENKINS
                    expression { return params.All || params.Dev }
                }
            }
            steps {
                dir(DIR) {
                    sh 'npm run build:dev'
                }
            }
        }

        stage('Deploy Dev') {
            when {
                anyOf {
                    changeset CHANGE_SRC
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    changeset JENKINS
                    expression { return params.All || params.Dev }
                }
            }
            steps {
                dir(DIR) {
                    scpBuildFilesToWWW(USERNAME, DOMAIN, DEV_CLIENT_HOSTNAME)
                }
            }
        }

        stage('Update Nginx Dev') {
            when {
                anyOf {
                    changeset "${DIR}/${DEV_NGINX_CONF}"
                    expression { return params.All || params.Dev }
                }
            }
            steps {
                dir(DIR) {
                    updateNginxConf(USERNAME, DOMAIN, DEV_CLIENT_HOSTNAME, DEV_NGINX_CONF)
                }
            }
        }

        stage('Build Prod') {
            when {
                expression { return params.All || params.Prod }
            }
            steps {
                dir(DIR) {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy Prod') {
            when {
                expression { return params.All || params.Prod }
            }
            steps {
                dir(DIR) {
                    scpBuildFilesToWWW(USERNAME, DOMAIN, PROD_CLIENT_HOSTNAME)
                }
            }
        }

        stage('Update Nginx Prod') {
            when {
                anyOf {
                    changeset "${DIR}/${PROD_NGINX_CONF}"
                    expression { return params.All || params.Prod }
                }
            }
            steps {
                dir(DIR) {
                    updateNginxConf(USERNAME, DOMAIN, PROD_CLIENT_HOSTNAME, PROD_NGINX_CONF)
                }
            }
        }
    }
}
