@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'All',
            defaultValue: false,
            description: 'Runs all even if there are no changes'
        )

        booleanParam(
            name: 'Dev',
            defaultValue: false,
            description: 'Runs dev even if there are no changes'
        )

        booleanParam(
            name: 'Prod',
            defaultValue: false,
            description: 'Runs prod even if there are no changes'
        )
    }

    environment {
        DEV_CLIENT_HOSTNAME = 'dev.tic-tac-toe.qrcool.ca'
        PROD_CLIENT_HOSTNAME = 'tic-tac-toe.qrcool.ca'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
        SERVER_USERNAME = credentials('server-username')
        SERVER_DOMAIN = credentials('server-domain')
        JENKINS = 'Jenkinsfile'
        CHANGE_SRC = 'api/**'
        DIR = 'api'
        SOLUTION_NAME = 'tic-tac-toe'
        PROJECT_NAME = 'tic-tac-toe.api'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Load secrets') {
            when { 
				changeset "${DIR}/**"
				expression { return params.All || params.Dev || params.Prod }	
			}
			steps {
                dir("${DIR}") {
                    loadAppsettings(PROJECT_NAME, 'Development')
                    loadAppsettings(PROJECT_NAME, 'Production')
                }
            }
        }

        stage('Build Docker Image') {
            when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Dev || params.Prod }	
				}
			}
			steps {
                echo "Building Docker image for ${DIR}..."
                buildDockerImage('api/Dockerfile', 'tic-tac-toe', 'latest')
            }
        }

        stage('Deploy Dev') {
			when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Dev }
				}
			}
            steps {
				dir(DIR) { 
                    scpDockerCompose(SERVER_USERNAME, SERVER_DOMAIN, SOLUTION_NAME, 'dev')
                    startDockerCompose(SERVER_USERNAME, SERVER_DOMAIN, SOLUTION_NAME, 'dev')
				}
            }
        }

        // TODO: GET SERVER USERNAME AND DOMAIN FROM JENKINS ENV
        stage('Deploy Prod') {
			when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Prod }
				}
			}
            steps {
				dir(DIR) { 
                    scpDockerCompose(SERVER_USERNAME, SERVER_DOMAIN, SOLUTION_NAME, 'prod')
                    startDockerCompose(SERVER_USERNAME, SERVER_DOMAIN, SOLUTION_NAME, 'prod')
				}
            }
        }
    }
}
