@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'All',
            defaultValue: false,
            description: 'Runs all even if there are no changes'
        )

        booleanParam(
            name: 'Dev',
            defaultValue: false,
            description: 'Runs dev even if there are no changes'
        )

        booleanParam(
            name: 'Prod',
            defaultValue: false,
            description: 'Runs prod even if there are no changes'
        )
    }

    environment {
        DEV_CLIENT_HOSTNAME = 'dev.tic-tac-toe.qrcool.ca'
        PROD_CLIENT_HOSTNAME = 'tic-tac-toe.qrcool.ca'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
        PACKAGE = 'client/package.json'
        PACKAGE_LOCK = 'client/package-lock.json'
        JENKINS = 'Jenkinsfile'
        CHANGE_SRC = 'api/src/**'
        DIR = 'api'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            when {
                anyOf {
                    changeset SRC
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    changeset JENKINS
                    expression { return params.All || params.Dev }
                }
            }
            steps {
                dir(DIR) {
                    sh 'npm run build:dev'
                }
            }
        }

        stage('Deploy Dev') {
            when {
                anyOf {
                    changeset SRC
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    changeset JENKINS
                    expression { return params.All || params.Dev }
                }
            }
            steps {
                dir(DIR) {
                    scpBuildFilesToWWW(USERNAME, DOMAIN, DEV_CLIENT_HOSTNAME)
                }
            }
        }

        stage('Deploy Prod') {
            when {
                expression { return params.All || params.Prod }
            }
            steps {
                dir(DIR) {
                    scpBuildFilesToWWW(USERNAME, DOMAIN, PROD_CLIENT_HOSTNAME)
                }
            }
        }
    }
}
