@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'All',
            defaultValue: false,
            description: 'Runs all even if there are no changes'
        )

        booleanParam(
            name: 'Dev',
            defaultValue: false,
            description: 'Runs dev even if there are no changes'
        )

        booleanParam(
            name: 'Prod',
            defaultValue: false,
            description: 'Runs prod even if there are no changes'
        )
    }

    environment {
        DEV_CLIENT_HOSTNAME = 'dev.tic-tac-toe.qrcool.ca'
        PROD_CLIENT_HOSTNAME = 'tic-tac-toe.qrcool.ca'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
        PACKAGE = 'client/package.json'
        PACKAGE_LOCK = 'client/package-lock.json'
        JENKINS = 'Jenkinsfile'
        CHANGE_SRC = 'api/src/**'
        DIR = 'api'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Dev || params.Prod }	
				}
			}
			steps {
                echo "Building Docker image for ${DIR}..."
                buildDockerImage('api/Dockerfile', 'tic-tac-toe', 'latest')
            }
        }

        stage('Deploy Dev') {
			when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Dev }
				}
			}
            steps {
				dir(DIR) { 
                    scpDockerCompose('miller', 'sys1.clarkmiller.ca', 'tic-tac-toe', 'dev')
                    startDockerCompose('miller', 'sys1.clarkmiller.ca', 'tic-tac-toe', 'dev')
				}
            }
        }

        // TODO: GET SERVER USERNAME AND DOMAIN FROM JENKINS ENV
        stage('Deploy Prod') {
			when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Prod }
				}
			}
            steps {
				dir(DIR) { 
                    scpDockerCompose('miller', 'sys1.clarkmiller.ca', 'tic-tac-toe', 'prod')
                    startDockerCompose('miller', 'sys1.clarkmiller.ca', 'tic-tac-toe', 'prod')
				}
            }
        }
    }
}
